# FTP to NextCloud - Kubernetes Deployment
#
# This example uses hostPort to expose passive FTP ports 30000-30009.
# The Service and Deployment both expose these 10 ports plus the control port 2121.
# 
# For more concurrent transfers, add more port entries in both Service and Deployment.
# Adjust PASV_MIN_PORT/PASV_MAX_PORT environment variables to match the exposed ports.
---
apiVersion: v1
kind: Service
metadata:
  name: ftp-to-nextcloud
spec:
  type: LoadBalancer
  selector:
    app: ftp-to-nextcloud
  ports:
    - protocol: TCP
      port: 2121
      targetPort: 2121
    - protocol: TCP
      port: 30000
      targetPort: 30000
    - protocol: TCP
      port: 30001
      targetPort: 30001
    - protocol: TCP
      port: 30002
      targetPort: 30002
    - protocol: TCP
      port: 30003
      targetPort: 30003
    - protocol: TCP
      port: 30004
      targetPort: 30004
    - protocol: TCP
      port: 30005
      targetPort: 30005
    - protocol: TCP
      port: 30006
      targetPort: 30006
    - protocol: TCP
      port: 30007
      targetPort: 30007
    - protocol: TCP
      port: 30008
      targetPort: 30008
    - protocol: TCP
      port: 30009
      targetPort: 30009
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-to-nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp-to-nextcloud
  template:
    metadata:
      labels:
        app: ftp-to-nextcloud
    spec:
      containers:
        - name: ftp-to-nextcloud
          image: ghcr.io/jbrunner/ftp-to-nextcloud:latest
          ports:
            - containerPort: 2121
            # Passive mode ports with hostPort
            - containerPort: 30000
              hostPort: 30000
              protocol: TCP
            - containerPort: 30001
              hostPort: 30001
              protocol: TCP
            - containerPort: 30002
              hostPort: 30002
              protocol: TCP
            - containerPort: 30003
              hostPort: 30003
              protocol: TCP
            - containerPort: 30004
              hostPort: 30004
              protocol: TCP
            - containerPort: 30005
              hostPort: 30005
              protocol: TCP
            - containerPort: 30006
              hostPort: 30006
              protocol: TCP
            - containerPort: 30007
              hostPort: 30007
              protocol: TCP
            - containerPort: 30008
              hostPort: 30008
              protocol: TCP
            - containerPort: 30009
              hostPort: 30009
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          env:
            - name: NEXTCLOUD_URL
              value: "https://nextcloud.example.com"
            - name: PASV_MIN_PORT
              value: "30000"
            - name: PASV_MAX_PORT
              value: "30009"
